version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 1
- package-ecosystem: gradle
  directory: "/android"
  schedule:
    interval: weekly
  open-pull-requests-limit: 1
  ignore:
  - dependency-name: io.sentry:sentry-android
    versions:
    - 4.2.0

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
      interval: weekly
